from agent.config.env_loader import (
    AGENT_EXTERNAL_APPROVAL_TTL_SECONDS,
    AGENT_REPLY_TIMEOUT_SECONDS,
    ASSISTANT_CONTEXT_TRANSCRIPT_SEGMENTS,
    ASSISTANT_COOLDOWN_SECONDS,
    ASSISTANT_DISPLAY_NAME,
    ASSISTANT_FALLBACK_REPLY_MESSAGE,
    ASSISTANT_LAST_QUESTION_TTL_SECONDS,
    CHAT_HISTORY_MAX_LEN,
    GEMINI_EMBEDDING_MODEL_NAME,
    GEMINI_MODEL_SUMMEREASE,
    HTTP_MAX_RETRIES,
    HTTP_TIMEOUT_SECONDS,
    JWT_EXPIRE_MINUTES,
    TRANSCRIPT_SEGMENTS_LIMIT,
)


class AgentConstants:
    SYSTEM_USER_ID: str = "system:assistant"
    SYSTEM_DISPLAY_NAME: str = ASSISTANT_DISPLAY_NAME

    STREAM_CALL_TYPE: str = "default"
    ASSISTANT_ENABLED_KEY_PREFIX: str = "assistant_enabled:"
    ASSISTANT_COOLDOWN_KEY_PREFIX: str = "assistant:cooldown:"
    ASSISTANT_LAST_QUESTION_KEY_PREFIX: str = "assistant:last_question:"

    JWT_EXPIRY_MINUTES: int = JWT_EXPIRE_MINUTES
    HTTP_TIMEOUT_SECONDS: float = HTTP_TIMEOUT_SECONDS
    HTTP_MAX_RETRIES: int = HTTP_MAX_RETRIES

    MIN_QUESTION_LENGTH: int = 3
    MIN_TRANSCRIPT_LENGTH: int = 50
    MAX_QUESTION_LENGTH: int = 200
    MAX_HISTORY_LENGTH: int = CHAT_HISTORY_MAX_LEN
    RECENT_TRANSCRIPT_LIMIT: int = TRANSCRIPT_SEGMENTS_LIMIT
    ASSISTANT_CONTEXT_TRANSCRIPT_SEGMENTS: int = ASSISTANT_CONTEXT_TRANSCRIPT_SEGMENTS

    ASSISTANT_COOLDOWN_SECONDS: int = ASSISTANT_COOLDOWN_SECONDS
    ASSISTANT_LAST_QUESTION_TTL_SECONDS: int = ASSISTANT_LAST_QUESTION_TTL_SECONDS

    FALLBACK_REPLY_MESSAGE: str = ASSISTANT_FALLBACK_REPLY_MESSAGE

    GEMINI_MODEL_NAME: str = GEMINI_MODEL_SUMMEREASE
    GEMINI_EMBEDDING_MODEL_NAME: str = GEMINI_EMBEDDING_MODEL_NAME

    AGENT_EXTERNAL_APPROVAL_TTL_SECONDS: int = AGENT_EXTERNAL_APPROVAL_TTL_SECONDS
    AGENT_REPLY_TIMEOUT_SECONDS: float = AGENT_REPLY_TIMEOUT_SECONDS
